server:
  port: 8080
  servlet:
    context-path: /

#\u6570\u636E\u6E90\u914D\u7F6E
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimeZone=GMT%2B&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLInnoDBDialect


